name: Demo Workflow   # Workflow name

on: push              # Trigger (runs on push)

jobs:
  build:              # Job name
    runs-on: ubuntu-latest

    steps:
      - name: Print message 
      - run: echo "Hello, GitHub Actions!"  # Step 2: Run command

